### ISSUE TITLE
Support for DeepSource version 0.7.2

### ISSUE THREAD

**Issue by mrobinsonlumint** [deepsourcelabs/homebrew-cli#9]
`brew install deepsourcelabs/cli/deepsource` fails with The requested URL returned error: 404 . Can you update this to support the latest DeepSource version (0.7.2) ?

<img width="832" alt="image1" src="https://github.com/DeepSourceCorp/homebrew-cli/assets/96447112/21247992-a067-4e3d-b1b1-4da1c3a2e682">

@siddhant-deepsource

**Comment by srijan-deepsource** [comment]
Hey @mrobinsonlumint. Installation via brew is now fixed.
Please make sure you delete any old cached tars. The current latest version `v0.8.2`.
